CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "name" varchar NOT NULL,
  "role" varchar NOT NULL,
  "gender" varchar(10) NOT NULL,
  "avatar" varchar,
  "created_at" timestamp DEFAULT 'now()'
);

CREATE TABLE "post" (
  "post_is" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(200) DEFAULT '',
  "body" text DEFAULT '',
  "og_image" varchar,
  "slug" varchar UNIQUE NOT NULL,
  "published" boolean,
  "created_by" integer DEFAULT 'now()'
);

CREATE TABLE "claps" (
  "clap_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" integer,
  "user_id" integer,
  "counter" integer DEFAULT 0,
  "created_at" timestamp
);

CREATE TABLE "commments" (
  "comments_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" integer,
  "user_id" integer,
  "content" text,
  "visible" boolean,
  "comment_parent_id" integer
);

CREATE TABLE "user_list" (
  "user_list_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "title" varchar(100)
);

CREATE TABLE "user_list_entry" (
  "user_list_entry" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_lost_id" integer,
  "post_id" integer
);

CREATE UNIQUE INDEX ON "claps" ("post_id", "user_id");

CREATE INDEX ON "claps" ("post_id");

CREATE INDEX ON "commments" ("post_id");

CREATE INDEX ON "commments" ("visible");

CREATE UNIQUE INDEX ON "user_list" ("user_id", "title");

CREATE INDEX ON "user_list" ("user_id");

ALTER TABLE "post" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("user_id");

ALTER TABLE "claps" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("post_is");

ALTER TABLE "claps" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "commments" ADD FOREIGN KEY ("comments_id") REFERENCES "post" ("post_is");

ALTER TABLE "commments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "commments" ADD FOREIGN KEY ("comment_parent_id") REFERENCES "commments" ("comments_id");

ALTER TABLE "user_list" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "user_list_entry" ADD FOREIGN KEY ("user_lost_id") REFERENCES "user_list" ("user_list_id");

ALTER TABLE "user_list_entry" ADD FOREIGN KEY ("post_id") REFERENCES "post" ("post_is");
